workflows:
  ios-workflow:
    name: aylaacademy ios_app_store 1713492560
    max_build_duration: 120
    integrations:
      app_store_connect: aylaacademy ios_app_store 1713492560
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier com.aylaacademy.bundleId:
        APP_STORE_APPLE_ID: com.aylaacademy.bundleId

    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles -p path/to/your/project
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: false